### ISSUE TITLE
For version 5.3 :)

### ISSUE THREAD

**Issue by ericmuigai** [svenluijten/artisan-view#10]
Would love it if you could add version 5.3 compatibility

**Comment by svenluijten** [comment]
Hey @ericmuigai! Yep, I'm currently rewriting the entire package in [the 2.0 branch](https://github.com/svenluijten/artisan-view/tree/2.0). I hope to have it finished by the end of the week :smile:

**Comment by ericmuigai** [comment]
Awesome :)

**Comment by svenluijten** [comment]
[Packagist was having some issues with package's metadata](https://twitter.com/packagist/status/772034610632990720) but I was just able to test the package on 5.3 and it works fine. Pull in [version 1.3.1](https://github.com/svenluijten/artisan-view/releases/tag/1.3.1) and you should be golden :thumbsup:
