### ISSUE TITLE
Laravel upgrade to 5.4

### ISSUE THREAD

**Issue by ghost** [svenluijten/artisan-view#21]
Can't upgrade Laravel to 5.4
Call to undefined method Illuminate\Foundation\Application::share()
As of laravel 5.4 share has been removed. You will have to use the singleton instead.

**Comment by svenluijten** [comment]
Hey, can you verify that #20 resolves this issue? I don't have the ability to check right now.

**Comment by ghost** [comment]
Thanks! I'll check it out.

**Comment by ghost** [comment]
Works, thanks!

**Comment by svenluijten** [comment]
Fixed in #20.
