### ISSUE TITLE
How about a --clone directive

### ISSUE THREAD

**Issue by webstractions** [svenluijten/artisan-view#22]
Being able to clone existing views, then making minor changes to them would be sweet. Currently, we just copy and paste code from one view to the other and modify that.

**Comment by patrikpihlstrom** [comment]
I second this

**Comment by svenluijten** [comment]
I love this idea! Will get working on it this weekend 😄

**Comment by webstractions** [comment]
@svenluijten Outstanding! 

This will come in handy for some of the more complex files. I have one that I use on index pages that uses jQuery DataTables with custom javascript in the footer. 

Heck, I can see just having a basic `stubs` folder to just clone your framework into place. So maybe an option to clone by the folder or individual file perhaps?

**Comment by vadis2** [comment]
This is the most useful command from my opinion. It saves a lot of time in a big project.

**Comment by chrisdicarlo** [comment]
Has anyone started working on this feature? I definitely see the usefulness.

**Comment by svenluijten** [comment]
I haven't, but to be fair this has quite a bit of overlap with #28, and I would prefer that over another option. The `make:view` command already has quite a few options and I'd like to keep it simple to use & find what you want.

**Comment by chrisdicarlo** [comment]
Just took a look at #28 and I agree.  I'll continue that discussion.

I wonder if this issue should just be closed with a reference to #28?

**Comment by svenluijten** [comment]
Definitely should! I've been neglecting this repository a bit 😅 Thanks for the kick in the butt, this was at the top of my todo list for a while but I just never _actually_ did it!

**Comment by chrisdicarlo** [comment]
LOL Yeah, I just came across the repo when I was starting to implement some of the functionality myself!  Lucky I did, saved me a bunch of work and it's actually more elegant than my solution was ever going to be!
