### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by mrmonat** [svenluijten/artisan-view#26]
Hi, unfortunately due to the composer.json of the 1.3.3 release, its not compatible with Laravel 5.5

> Problem 1
    - Installation request for sven/artisan-view ^1.3.3 -> satisfiable by sven/artisan-view[1.3.3].
    - Conclusion: remove laravel/framework v5.5.0
    - sven/artisan-view 1.3.3 requires illuminate/support 5.0.* || 5.1.* || 5.2.* || 5.3.* || 5.4.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].

**Comment by svenluijten** [comment]
I'm aware 😄 I'm busy working on [the 2.0 branch](https://github.com/svenluijten/artisan-view/tree/2.0), which will be a complete rewrite and 100% compatible with Laravel 5.5!

**Comment by svenluijten** [comment]
Actually, that doesn't make sense. I added auto-discovery in a previous commit in the `master` branch, so I'll update the version constraint in `composer.json` as well. [Version 1.3.4](https://github.com/svenluijten/artisan-view/releases/tag/v1.3.4) supports Laravel 5.5!
