### ISSUE TITLE
Error When Trying to Generate View

### ISSUE THREAD

**Issue by adriangordon1231** [svenluijten/artisan-view#29]
I installed this package in a fresh lareval 5.5 project, however when I try to actually use it to generate a view I get the following error

![error](https://user-images.githubusercontent.com/7938253/30408298-bd6ad974-98cb-11e7-9df8-2f02ad778e92.png)

I have tried using it with and without registering '\Sven\ArtisanView\ServiceProvider::class' in my service provider class. 

Any clues as to why it would not work?

**Comment by svenluijten** [comment]
What version of PHP do you have running? Eg, what's the output of `php -v` on your system? Just like Laravel 5.5, this package requires PHP 7 and its new `iterable` pseudo-type.

**Comment by adriangordon1231** [comment]
I am running php 7.0.23

**Comment by bbcreation** [comment]
Hi; I have the same problem in PHP 7.0.9

**Comment by svenluijten** [comment]
I've released [version 2.0.1](https://github.com/svenluijten/artisan-view/releases/tag/2.0.1) to fix this, can you try running `composer update sven/artisan-view`? 🙂

**Comment by bbcreation** [comment]
it works!

**Comment by svenluijten** [comment]
Great, thanks for the confirmation 👍
