### ISSUE TITLE
does that package implement the method in a specified controller?

### ISSUE THREAD

**Issue by brian-lamb-software-engineer** [svenluijten/artisan-view#31]
My idea, when i found [this article](https://github.com/laravel/internals/issues/241), which lead me to here, was I was hoping to see if artisan had a way to generate a view, and add a method which returns that view, in one swoop, to an existing controller, which is specified.  I was surprised when i came here, this package either doesn't do that, or I cant find that info in the readme.  Im not normally one to dig through packages to find features, I feel they should be prominently displayed on the readme.  

Does this have that that feature, or does someone know if a package that does?  That's the only way I can see justifying the need to generate a view.

Thanks!

**Comment by svenluijten** [comment]
No, this package can't do that. Though I suppose you could _hack_ it in:

```php
class YourController
{
    public function doThing()
    {
        $name = 'name-of-view';

        Artisan::call('make:view', [
            'view' => $name,
        ]);

        return view($name);
    }
}
```

> That's the only way I can see justifying the need to generate a view.

What do you mean by that? This package isn't really made to be used like you describe, it's more of a way for the developer to generate a view stub that they can customize later on (like `php artisan make:controller` or `php artisan make:migration` in the Laravel core).

**Comment by svenluijten** [comment]
@brian-lamb-software-engineer Hey, did you get a chance to look at this? Been a week without a response now 🙂

**Comment by brian-lamb-software-engineer** [comment]
Thanks for your response, I will try something like that when I get back to that package.  As far as what i meant by 
> That's the only way I can see justifying the need to generate a view.

The main thing I was trying to avoid was not making the view file, it was the redundant editing in the controller for a new view.  If I scaffold only the view, I will still need to do the groundwork of stubbing the controller method, mostly each and every time. I was aiming for your `scaffold` feature hoping it can put the entry into a controller.  I can already copy one of my other view examples.  It would be less work for me to `ctrl c`, `ctrl v` any existing view file in `atom`, and edit from there, without having lookup the correct `php artisan make:view ` commands to make them.   

If you can add a switch for that feature, It would be very useful for me.  E.g. If i can `php artisan make:view reports --controller=DashboardController` and it would automatically stub a reports method in the controller with a view return method, that would be great. 
e.g.
```
    /**
     * reports
     * 
     * @return \Illuminate\Http\Response
     */
    public function reports()
    {

      return view('dashboard.report',[
        ]);
    }
```

**Comment by svenluijten** [comment]
Sorry, but I'm afraid that's outside of the scope of this package. For now you're going to have to keep <kbd>CTRL</kbd> + <kbd>C</kbd> / <kbd>CTRL</kbd> + <kbd>V</kbd>'ing 😉
