### ISSUE TITLE
Can not create view

### ISSUE THREAD

**Issue by vuuvinhphuc** [svenluijten/artisan-view#32]
Hello Seven,
I'm newbie Laravel, after I installed artisan-view add registered services provider I run command bellow. Then Exception throw. Please help me!! Thanks Seven a lot.
C:\xampp7\htdocs\sample-project>**php artisan make:view settings.edit**

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to Sven\ArtisanView\ViewActor::getViewNames() must be an instance of Sven\ArtisanView\iterable, array given, called in C:\xampp7\htdocs\sample-proj
  ect\vendor\sven\artisan-view\src\Generator.php on line 17

**Comment by svenluijten** [comment]
Yeah, this was an issue in version 2.0.0. It has been fixed in [2.0.1](https://github.com/svenluijten/artisan-view/releases/tag/2.0.1), though. 

Can you try running `composer update sven/artisan-view` to update the package to the latest version and then try creating the view again?

**Comment by vuuvinhphuc** [comment]
Thank you Sven for quick response. I will try it

**Comment by svenluijten** [comment]
Hey @vuuvinhphuc, did this solve the issue? Let me know so I can close the issue 🙂

**Comment by vuuvinhphuc** [comment]
Thanks Sven, I've resolved already. Sorry replay late
