### ISSUE TITLE
What are the install requirements of this package? 

### ISSUE THREAD

**Issue by fredbradley** [svenluijten/artisan-view#40]
When I install (via composer) as per the instructions in the README. 

I get: 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php 7.0.* but your PHP version (7.2.4) does not satisfy that requirement.
```

But you say it works on Laravel 5.6? Which doesn't work on anything less than 7.2? 

Please confirm. ?

**Comment by svenluijten** [comment]
Hi @fredbradley,

Version 3.x of this packages requires PHP 7.1 or above, as you can see in [the `composer.json`](https://github.com/svenluijten/artisan-view/blob/v3.0.0/composer.json#L14). Version 2.x requires PHP 7.0 or above, per [its `composer.json`](https://github.com/svenluijten/artisan-view/blob/v2.1.0/composer.json#L14).

You can use the version dropdown on that page to look at the requirements for other versions: 

![screenshot](https://i.imgur.com/MPgn0Eo.png)

Though it looks like the error you're getting doesn't come from this package (the `php` version constraint has never been `7.0.*` on a tagged version of artisan-view). Can you post the full output you're getting from Composer? I'll do some more digging to figure this out 🙂

**Comment by fredbradley** [comment]
You're 100% right... I was being too quick and jumped to conclusions! 

Sorry, my bad!
