### ISSUE TITLE
Add Content "HTML" in Section 

### ISSUE THREAD

**Issue by sharjeelz** [svenluijten/artisan-view#42]
Can we add section's content? 

```blade
@section('content')

<h1>Hllo</h1>
</h3>ok</h3>

@endsection
```

**Comment by svenluijten** [comment]
I think that's a bit out of scope for this project... Artisan View is just there to create your view files. You'd still need to use your editor/IDE to fill the view with the content you want. 

If this would be implemented, how would it work?

```bash
$ php artisan make:view --section="content:Hello world"
```

This already creates a view with an inline section: 

```blade
@section('content', 'Hello world')

```

**Comment by sharjeelz** [comment]
I mean If I want to generate CRUD operation files. I want to fill the content section with a Stub of HTML or Part of HTML to be included in it, and I can edit it from there.

**Comment by sharjeelz** [comment]
Also, I need your email address to contact you personally . if you don't mind. I want to learn from you.

**Comment by svenluijten** [comment]
Adding a stub of HTML in a view really isn't in scope of this package I'm afraid.

To contact me, you can DM me on [Twitter](https://twitter.com/svenluijten) or reach me via [Keybase chat](https://keybase.io/svenluijten).
