### ISSUE TITLE
Incompatible with PHP7?

### ISSUE THREAD

**Issue by MadBulgarian** [svenluijten/artisan-view#43]
For some reason, I had to use version 2.1 of artisan-view (still works fine). I am using PHP 7.0.31
Error: 
Package sven/artisan-view at version ^3.0 has a PHP requirement incompatible with your PHP version (7.0.31)

**Comment by svenluijten** [comment]
Yes, version 3.0+ of this package [requires PHP 7.1](https://github.com/svenluijten/artisan-view/blob/v3.0.0/composer.json#L14).
