### ISSUE TITLE
Get rid of confusing "Voter" name

### ISSUE THREAD

**Issue by svenluijten** [svenluijten/artisan-view#47]
I'd much rather have something more descriptive of what it does, or even something closer to the "blocks" concept already in the code. This needs to be worked out.

**Comment by chrisdicarlo** [comment]
I agree.  For anyone looking at the code base, it's confusing.

**Comment by svenluijten** [comment]
fixed in https://github.com/svenluijten/artisan-view/commit/ca5d4975571df552a1ef4ee4c6d10eed1e9ec3ef
