### ISSUE TITLE
No Support for Laravel 5.7.3

### ISSUE THREAD

**Issue by Zugmaschine** [svenluijten/artisan-view#54]
Is there a way to use that package in Laravel V 5.7.3?

**Comment by svenluijten** [comment]
Hey @Zugmaschine, I just checked it out and it's working fine for me: 

![screenshot on imgur](https://i.imgur.com/kRm88bN.png)

Did you already have the package installed when you updated to Laravel 5.7.3? If so, is it in your `composer.json`'s `require-dev` or `require` blocks? What error are you getting?

**Comment by furatamasensei** [comment]
This happened to me too in V5.7.11

![screenshot 5](https://user-images.githubusercontent.com/42239243/47608430-ce1fca80-da57-11e8-9581-72cadd5c31cc.png)

**Comment by furatamasensei** [comment]
> This happened to me too in V5.7.11
> 
> ![screenshot 5](https://user-images.githubusercontent.com/42239243/47608430-ce1fca80-da57-11e8-9581-72cadd5c31cc.png)

woops, I just resolved it by removing the specific version value just like @svenluijten did.

**Comment by svenluijten** [comment]
Ah yes @pratamatama, Laravel 5.7 is only supported on `3.1.*` of this package. I'll remove the specific version from the README's instructions, Composer will resolve the version automatically anyway :)

**Comment by svenluijten** [comment]
There we go: https://github.com/svenluijten/artisan-view/commit/4b6c76548115a9e374d5e8cb053535c8e8f52eb7

@Zugmaschine can you confirm that not specifying the version (`^3.1`) in the command fixes your issue?
