### ISSUE TITLE
Create view copying all the content

### ISSUE THREAD

**Issue by lflucasferreira** [svenluijten/artisan-view#55]
Hi!

I would like to ask you to implement the tag --duplicate. This would help me to copy all the content from a view just changing the filename and the references inside it.

Cheers.

**Comment by svenluijten** [comment]
Hi! Would #28 (the idea of "presets") also be a good solution for this? Or do you think duplicating a view still has some benefit besides that?

**Comment by lflucasferreira** [comment]
Well, I am not sure if the presets idea covers just the need of copying. But I believe you know better than me. So, the decision is on yours hands. By the way, thank you for spending your time on this matter.

**Comment by svenluijten** [comment]
This package has been abandoned because of the introduction of the new `make:view` command included in Laravel since [v10.23.0](https://github.com/laravel/framework/releases/tag/v10.23.0). For that reason, this issue will _not_ be worked on.
