### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by aetonsi** [svenluijten/artisan-view#63]
Hi!
Would it be possible to have support for the Lumen framework?

Currently, it **is** possible to require this package in a Lumen project.
The problem is, it requires the entire `laravel/framework` as a dependency. This breaks composer if some `illuminate/*` package is also required.

For example, i required `illuminate/mail` to have mailing functionality in my project.
If i then try to install this package, **sometimes** composer breaks up, other times it lets me install it.
But even the few times it installs, other things break. An example:
```log
PHP Fatal error:  Uncaught ReflectionException: Class path.storage does not exist in A:\projects\_tmp\lumen\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
Stack trace:
#0 A:\projects\_tmp\lumen\vendor\laravel\framework\src\Illuminate\Container\Container.php(805): ReflectionClass->__construct('path.storage')
#1 A:\projects\_tmp\lumen\vendor\laravel\framework\src\Illuminate\Container\Container.php(687): Illuminate\Container\Container->build('path.storage')
#2 A:\projects\_tmp\lumen\vendor\laravel\framework\src\Illuminate\Container\Container.php(633): Illuminate\Container\Container->resolve('path.storage', Array)
#3 A:\projects\_tmp\lumen\vendor\laravel\lumen-framework\src\Application.php(267): Illuminate\Container\Container->make('path.storage', Array)
#4 A:\projects\_tmp\lumen\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(119): Laravel\Lumen\Application->make('path.storage', Array)
#5 A:\projects\_tmp\lumen\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(832): app('path.stora in A:\projects\_tmp\lumen\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 807

Fatal error: Uncaught ReflectionException: Class path.storage does not exist in A:\projects\_tmp\lumen\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 807

Illuminate\Contracts\Container\BindingResolutionException: Target class [path.storage] does not exist. in A:\projects\_tmp\lumen\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 807

...
```

It seems like this mess happens whenever a package has the entire Laravel framework as a dependency: [laravel/lumen-framework/issues/870#issuecomment-516780947](https://github.com/laravel/lumen-framework/issues/870#issuecomment-516780947) (see also laravel/lumen-framework#798 , laravel/lumen-framework#504).

So, i'm asking if it would be possible to include just the bare necessary `illuminate`, `symfony`, ecc submodules instead of the entire framework, so that it would work even with Lumen.
As an example, check out [flipbox/lumen-generator](https://packagist.org/packages/flipbox/lumen-generator)'s `requires`.

<hr>

Thank you for your time,
Have a nice day

**Comment by svenluijten** [comment]
It makes very little sense to me why you would want to generate views in Lumen, seeing as it's a microframework intended to be used for making APIs. I think it would be hard to justify the effort (+ maintenance burden) to support something that's not useful in my mind.

If you really wanted this (or similar) functionality in Lumen, you're better off writing a custom artisan command and doing it in there to be honest 🤷

**Comment by aetonsi** [comment]
Hi, thanks for your reply.

I didn't think i would need views in Lumen until today, when i discovered that the Lumen façade `Mail` is the same as Laravel's, and this means generating (`Illuminate\Mail\`)`Mailable` objects via `artisan make:mail`. These `Mailable`s use **blade templates** as body for the emails to send.
Quoting from [here](https://lumen.laravel.com/docs/7.x/mail):

> The Lumen mail drivers utilize the same code as the Laravel mail drivers. Beyond configuration, there are no differences between sending mail in Lumen and sending mail in Laravel; therefore, please consult the [full Laravel documentation](https://laravel.com/docs/7.x/mail) for usage examples.

And both the `->view()` and `->text()` methods for setting the email body require a `path.to.a.blade.view` (ref [here](https://laravel.com/docs/7.x/mail#configuring-the-view)).


If it's too cumbersome to adapt the code for Lumen, nevermind, don't worry. I fully understand.

Have a nice day/evening

**Comment by svenluijten** [comment]
Hmm that's fair, I didn't think about mails! Honestly I still think the usecase is a bit too narrow. Lumen is kind of neglected in the ecosystem already (I do realize I'm contributing to that neglicence by not adding support 😅 ), so I wonder how big an impact it would have to add Lumen support here.

I would consider a PR that adds support for Lumen though, so feel free if you want!

**Comment by svenluijten** [comment]
Closing this issue now, feel free to re-open or open a new one if it's still something you're interested in.
