### ISSUE TITLE
load livewire component in content section

### ISSUE THREAD

**Issue by ehsantalkhouncheh** [svenluijten/artisan-view#70]
@svenluijten  First of all, Thank you so much for really good and useful package, If we have a chance to load livewire component in content section then we could make a powerful page builder do you have any idea, Is it possible?

php artisan make:view test --section='title:test' --section='content:@livewire("component name")'

**Comment by svenluijten** [comment]
Hi @ehsantalkhouncheh, the `--section="content:<something>"` syntax (with the `:` in there) is reserved for inline sections only (like `@section('content', '<something>')`. So what you describe is currently not possible.

I don't see a lot of value in building support for a full page-builder type component like you describe either, as the aim for this package is just quickly scaffolding views. Just like how the `make:model` and `make:controller` commands in Laravel already are fairly stripped down, so is `make:view` here.

Thanks for the suggestion, but for now, I suggest you just build your views like normal.

**Comment by ehsantalkhouncheh** [comment]
Hi @svenluijten  Thanks for quick reply and your explanation, I guess you're right, But add simple text to content section is not useful, Anyway i know the main idea and I'm agree with you to keep it simple.
