### ISSUE TITLE
can i fill the the content section 

### ISSUE THREAD

**Issue by syofyanzuhad** [svenluijten/artisan-view#73]
i just try to fill the content section with many html like this :
![image](https://user-images.githubusercontent.com/52684582/113364999-2113af80-937f-11eb-8bec-115889287573.png)

but its return an error :
![image](https://user-images.githubusercontent.com/52684582/113365082-62a45a80-937f-11eb-855c-402c82b83210.png)

and this is my entire of content section :

is there any solution ?
```
<body style="margin-bottom: 29px;">
   
   <img src="https://api.pondokprogrammer.com/img/sertifikat/sertifikat-2.png" alt="" width="100%" id="background" style="position: absolute; z-index: -1">
   <div class="background pt-2 mt-5">
      <div class="my-5 p-auto" style="margin: 2%; padding: 0px; text-align:center; ">
         
         <div class="container" style="z-index: 0; position: absolute">
            <div class="row" style="display: flex; justify-content: center">
               <div style="margin-left: 115.7%; margin-top: 2%">
                  <img style="margin-top: 18%; margin-right: 110%;" width="100" src="https://api.pondokprogrammer.com/img/pondok-programmer.png" alt="logo">
               </div>
               <div style="margin-left: 15%; width: 200%">
                  <h1 style="margin-right: 50%; z-index: 0; position: absolute" class="font-weight-bold mt-3">CERTIFICATE OF COMPLETION</h1>
               </div>
            </div>
         </div>
         <div style="margin-top: 20%">
            <div style="text-align: left; margin-left: 10%">
               <span style="font-size:25px"><i>This is to certify that</i></span>
               <br>
               <span style="font-size:40px"><b>Syofyan Zuhad</b></span><br>
               <span style="font-size:25px"><i>has completed the study at</i> <span class="text-info">Pondok Programmer</span><i> in </i>:</span> <br><br>
               <span style="font-size:30px" class="text-info">Laravel Backend Development</span> <br>
               <span style="font-size:20px">with score of <span class="text-info font-weight-bold display-4">A+</span></span> 
               <br><br>
            </div>
               <table align="center" class="table text-center mt-3" style="border: none !important;">
                  <tbody><tr>
                     <td>
                        <span style="font-size:20px"><i>Syofyan Zuhad <small class="text-muted">- Mentor Backend</small></i></span><br><br><br><br>
                     </td> 
                     <td>
                        
                     </td>
                     <td>
                        <span style="font-size:20px"><i>Hafif Albusyro <small class="text-muted">- Chief</small></i></span><br><br><br><br>
                     </td>
                  </tr>
                  <tr>
                     <td>
                        Thursday, 
                        <span style="font-size:20px">01 April 2021</span>
                     </td>
                     <td width="10px">
                        <div style="margin-top: -20%; padding: 0px">
                           <img width="100" src="https://chart.googleapis.com/chart?cht=qr&amp;chs=130x130&amp;chl=https://api.pondokprogrammer.com/certificate/TuhWmpBLG&amp;choe=UTF-8" alt="qr">
                        </div>
                     </td>
                     <td>
                        Thursday, 
                        <span style="font-size:20px">01 April 2021</span>
                     </td>
                  </tr>
               </tbody></table>
            </div>
         </div>
      </div>
   
</body>
```

**Comment by svenluijten** [comment]
This package really isn't meant for such complex scenarios, but can you try showing me the full `$command` you're trying to run? I assume because of some spaces and/or other special characters in `$request->content`, it's having issues.

Also, why are you using artisan commands for this? You could also use the classes directly:

```php
use Sven\ArtisanView\Generator;
use Sven\ArtisanView\Config;
use Sven\ArtisanView\Blocks\Extend;
use Sven\ArtisanView\Blocks\InlineSection;

$generator = new Generator(new Config(/* your options */), $path);
$generator->makeViews(['sertifikat.'.$request->id_sertifikat], [
    new Extend('sertifikat.app'),
    new InlineContent('content', $request->content),
]);
```

**Comment by svenluijten** [comment]
Just circling back to this... The docs mention you should use quotes around the value of `--section` if you want to be able to use spaces. So you should use `--section=\"content:$request->content\"";` in your code, and that should work @syofyanzuhad.

**Comment by syofyanzuhad** [comment]
> This package really isn't meant for such complex scenarios, but can you try showing me the full `$command` you're trying to run? I assume because of some spaces and/or other special characters in `$request->content`, it's having issues.
> 
> Also, why are you using artisan commands for this? You could also use the classes directly:
> 
> ```
> use Sven\ArtisanView\Generator;
> use Sven\ArtisanView\Config;
> use Sven\ArtisanView\Blocks\Extend;
> use Sven\ArtisanView\Blocks\InlineSection;
> 
> $generator = new Generator(new Config(/* your options */), $path);
> $generator->makeViews(['sertifikat.'.$request->id_sertifikat], [
>     new Extend('sertifikat.app'),
>     new InlineContent('content', $request->content),
> ]);
> ```


no, no, no, OK that's a good idea..
but the problem is not right there..
the error was returned cause of your code right here :
![image](https://user-images.githubusercontent.com/52684582/113460315-854b7780-9442-11eb-89bc-fe53b21fd297.png)
at `Voters/SectionsInParent.php`
and the inline css has many ":" (colon)..
like this : `<span style="font-size:20px">01 April 2021</span>`

**Comment by svenluijten** [comment]
Right, that makes sense. I hope the solution I gave you earlier is sufficient for now @syofyanzuhad 🙂
