### ISSUE TITLE
Does this create BREAD? Or just index?

### ISSUE THREAD

**Issue by s3w47m88** [svenluijten/artisan-view#82]
Please forgive me if this is not the appropriate place for a question.

I'm considering using this but I'm fairly new to Laravel and I'm wondering if this generates all of the BREAD files or just a single index file?

**Comment by svenluijten** [comment]
Hi @s3w47m88, this should all be explained in the README. You can use the command `make:view` to create as many view files as you want:

- `php artisan make:view index` creates `resources/views/index.blade.php`
- `php artisan make:view something-else` creates `resources/views/something-else.blade.php`

See the README for more information :)
