### ISSUE TITLE
Default extends or section from config

### ISSUE THREAD

**Issue by CasperLaiTW** [svenluijten/artisan-view#9]
How about create the config to setting default extends or default section?

config

``` php
return [
    'extends' => 'layout',
    'section' => 'title,content'
];
```

If the config was published,

Run `php artisan make:view index` mean `php artisan make:view index --extends=layout --section=title,content`

**Comment by svenluijten** [comment]
Honestly I'm not a fan, kind of takes the whole aspect of control via artisan away from the developer. I'd like to keep it a bit simpler than this :smile:

**Comment by CasperLaiTW** [comment]
Ok, I understand! Thank you for your response. 😄
