### ISSUE TITLE
copy button for composer install copies dollar sign

### ISSUE THREAD

**Issue by lotje-kinable** [svenluijten/artisan-view#94]
Hi

this is super minor, but in every project I start, I use the package! And every time I copy the composer command from the docs, using the button... and have to come back and copy it without the $ sign manually. Would it be possible to adapt the docs? 

thanks in advance!!
Lotje

**Comment by svenluijten** [comment]
Sure thing! Would you mind submitting a PR?

**Comment by lotje-kinable** [comment]
Of course!

It's been a while though!
