### ISSUE TITLE
Lack of checking if the view exists

### ISSUE THREAD

**Issue by szajens** [svenluijten/artisan-view#96]
During the creation of the view using the make:view package, the existing file is overwritten and cleared

**Comment by magic-thomas** [comment]
I agree with this. It should not delete existing file or ask what todo. 

I really need this.

**Comment by svenluijten** [comment]
This package has been abandoned because of the introduction of the new `make:view` command included in Laravel since [v10.23.0](https://github.com/laravel/framework/releases/tag/v10.23.0). For that reason, this issue will _not_ be worked on.
